# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "vm-4-mm-IT" do |config|
    
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "docker-vm"
    config.vm.network "forwarded_port", guest: 3030, host: 3030
    config.vm.network "forwarded_port", guest: 8175, host: 8175

    config.vm.provision "shell", path: "kb/bootstrap.sh"
    config.vm.provision "shell", run: "always", path: "kb/startup.sh"

    config.vm.provision "shell", path: "dda/bootstrap.sh"
    config.vm.provision "shell", run: "always", path: "dda/startup.sh"


    # http://fgrehm.viewdocs.io/vagrant-cachier
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
    end

  end
end
