# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "docker-vm" do |config|
    
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "docker-vm"
    config.vm.network "forwarded_port", guest: 3030, host: 3030
    config.vm.network "forwarded_port", guest: 8175, host: 8175

    # config.vm.provision "docker" do |d|
    #   d.build_image "/vagrant/kb", args: "-t modaclouds/kb"
    #   d.build_image "/vagrant/dda", args: "-t modaclouds/dda"
    # end
    config.vm.provision "docker", run: "always" do |d|
      d.run "mmiglier/modaclouds-kb", args: "-p 3030:3030"
      d.run "mmiglier/modaclouds-dda", args: "-p 8175:8175"
    end

    # http://fgrehm.viewdocs.io/vagrant-cachier
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
    end

    # config.vm.provider "virtualbox" do |vb|
    #   vb.customize ["modifyvm", :id, "--memory", "2048"]
    # end
  end
end
